### PR TITLE
Mobile setup branch

### PR DESCRIPTION
**Pull request by Young-Gaius**
To create this milestone I used the following:

- Added index.html file
- Added style.css
- Added a readme file 
- Used linters

### CODE REVIEW

**Review by bellom — CHANGES_REQUESTED** [review]
@Young-Gaius, 

### This is a manual review

## Request Changes ♻️ 

You need to stick to the[ project requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md).

Your design doesn't match what we have in the Figma design given.

Your design:
image

Figma design: [link](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?type=design&node-id=1-468&t=PykSVb4dgONxYSys-0)

Kindly work on the design and let us know.

Cheers, and Happy coding!:clap::clap::clap:

**Comment by Young-Gaius** [comment]
Mobile setup branch by Young-Gaius · Pull Request #1 ·
Young-Gaius/portfolio-setup (github.com)
<https://github.com/Young-Gaius/portfolio-setup/pull/1>

**Comment by bellom** [comment]
@Young-Gaius thank you.

I'm afraid you are missing the work section and the About page.

I shared with you the project requirement in my comment above and I said you should stick to it, can you please implement it according to the project requirement?

Thank you.

**Comment by Young-Gaius** [comment]
Ok I will do that thank you 😊

**Comment by Young-Gaius** [comment]
mobile-portfolio by Young-Gaius · Pull Request #2 ·
Young-Gaius/portfolio-setup (github.com)
<https://github.com/Young-Gaius/portfolio-setup/pull/2>
This is the link to the project.
Please I will be waiting for your reply so I can proceed with my project.
Thanks

**Pull request merged**
